version: '3'
services:
  server1:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - RPC_URL=http://0.0.0.0:8547
      - STORE_DATA=TRUE
    env_file:
      - .env
    network_mode: host

  server2:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - RPC_URL=http://0.0.0.0:8548
    env_file:
      - .env
    network_mode: host

  server3:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - RPC_URL=http://0.0.0.0:8549
    env_file:
      - .env
    network_mode: host

  server4:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - RPC_URL=http://0.0.0.0:8550
    env_file:
      - .env
    network_mode: host
